app = 'storyteller'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[mounts]
  source = "litefs"
  destination = "/var/lib/litefs"

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
